### ISSUE TITLE
Dark Chai Theme comment tag is too bright

### ISSUE THREAD

**Issue by asimar007** [hiteshchoudhary/vscode-theme#3]
The Dark Chai Theme currently has a comment tag that appears to be too bright, causing discomfort and strain on the eyes during extended coding sessions. In my opinion, it would greatly enhance the user experience if the brightness of the comment tag could be dimmed.

![Screenshot 2023-12-08 at 8 20 13 PM](https://github.com/hiteshchoudhary/vscode-theme/assets/108481922/8b491f75-c4fa-4c16-9bdf-4c0ec1c628a7)

Light chai Theme comment tag is fine

**Comment by vaibhavc2** [comment]
> The Dark Chai Theme currently has a comment tag that appears to be too bright, causing discomfort and strain on the eyes during extended coding sessions. In my opinion, it would greatly enhance the user experience if the brightness of the comment tag could be dimmed.
> 
> ![Screenshot 2023-12-08 at 8 20 13 PM](https://private-user-images.githubusercontent.com/108481922/289106410-8b491f75-c4fa-4c16-9bdf-4c0ec1c628a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODc1NDUsIm5iZiI6MTcwNDI4NzI0NSwicGF0aCI6Ii8xMDg0ODE5MjIvMjg5MTA2NDEwLThiNDkxZjc1LWM0ZmEtNGMxNi05YmRmLTRjMGVjMWM2MjhhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMzA3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWFlM2YxNzc1NDAxZTY2YzFhZjU4NTBlNjNjMTFlMDcwMWNkYzM0ZmYzZjAzOTM0NWIwNzA0ZGQxZGMzZjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HGeKvYZmKWZ5pGDohFWa_VA8QNqzATcwiAMrIklnxKU)
> 
> Light chai Theme comment tag is fine

I am also using this theme since about more than three weeks, and I haven't noticed this bug even once! Comments are always in a dull gray shade which is really easy to read, but at the same time, doesn't obstruct the code.

![image](https://github.com/hiteshchoudhary/vscode-theme/assets/73025956/3d35552f-693d-4ad8-b8f5-48900fcc4466)

**Comment by m-shahzab** [comment]
1. Locate the settings file:
Begin by navigating to the settings file, specifically the settings.json file.
2. Find the designated section:
Within the settings.json file, seek out the section labeled "editor.tokenColorCustomizations"
3. Insert the code snippet:
Carefully paste the following code into that section:
JSON
"comments": "#colorCode"
4. Save the changes:
To ensure the modifications take effect, save the settings.json file.

![image](https://github.com/hiteshchoudhary/vscode-theme/assets/53417414/f73b4673-d11b-4fad-b898-32c3899d2b91)
